batch_size: 8
data_path: data/video7019
device: cuda
guidance_scale: 7.5
latents_path: latents
n_frames: 38
n_inversion_steps: 500
n_timesteps: 50
negative_prompt: ugly, blurry, low res, unrealistic, unaesthetic
output_path: tokenflow-results_pnp_SD_2.1/video7019/a man with suit sitting on the
  chair talking in front of the camera/attn_0.5_f_0.8/batch_size_8/50
pnp_attn_t: 0.5
pnp_f_t: 0.8
prompt: a man with suit sitting on the chair talking in front of the camera
sd_version: '2.1'
seed: 1
