device: cuda
enable_xformers_memory_efficient_attention: true
float_precision: fp16
generation:
  adapter_name: pixel
  adapter_weights: 1.0
  align_batch: true
  chunk_ord: mix-4
  chunk_size: 4
  control: pnp
  control_scale: 1.0
  frame_ids: null
  frame_range:
  - 0
  - 32
  - 1
  global_merge_ratio: 0.8
  global_rand: 0.5
  guidance_scale: 7.5
  latents_path: ${work_dir}/latents
  local_merge_ratio: 0.9
  lora_weight: 0.5
  merge_global: true
  n_timesteps: 50
  negative_prompt: ugly, blurry, low res
  output_path: ${work_dir}
  pnp_attn_t: 0.5
  pnp_f_t: 0.8
  pretrained_model_name_or_path_or_dict: null
  prompt:
  - prompt1: a boy is playing skateboard on the ground
  save_frame: true
  use_lora: false
  weight_name: PixelArtRedmond15V-PixelArt-PIXARFK.safetensors
height: 512
input_path: data/skateboard-man.mp4
inversion:
  batch_size: 8
  control: none
  control_scale: 1.0
  force: false
  n_frames: null
  prompt: a man is playing skateboard on the ground
  recon: false
  save_intermediate: true
  save_path: ${work_dir}/latents
  save_steps: 50
  steps: 50
  use_blip: false
model_key: null
sd_version: '1.5'
seed: 123
width: 512
work_dir: outputs/skateboard-man
