pretrained_model_path: /root/autodl-tmp/cache_huggingface/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base/
output_dir: outputs/video7027
input_data:
  video_path: data/data_used/video7027.mp4
  prompt: there is graphics of the universe in blue showing in tv
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 4
validation_data:
  prompts:
  - there is graphics of the universe in green showing in tv
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5
  num_inv_steps: 50
  # args for null-text inv
  use_null_inv: True
  null_inner_steps: 1
  null_base_lr: 1e-2
  null_uncond_ratio: -0.5
  null_normal_infer: True

input_batch_size: 1
seed: 33
mixed_precision: "no"
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
# test-time adaptation
use_sc_attn: True
use_st_attn: True
st_attn_idx: 0