enable_xformers_memory_efficient_attention: true
gradient_checkpointing: true
input_batch_size: 1
input_data:
  height: 512
  n_sample_frames: 8
  prompt: Female athletes perform pole vaulting
  sample_frame_rate: 4
  sample_start_idx: 0
  video_path: data/data_new/video18.mp4
  width: 512
mixed_precision: 'no'
output_dir: outputs/video18
pretrained_model_path: /root/autodl-tmp/cache_huggingface/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base/
seed: 33
st_attn_idx: 0
use_sc_attn: true
use_st_attn: true
validation_data:
  guidance_scale: 7.5
  height: 512
  null_base_lr: 1e-2
  null_inner_steps: 1
  null_normal_infer: true
  null_uncond_ratio: -0.5
  num_inference_steps: 50
  num_inv_steps: 50
  prompts:
  - Female athletes perform pole vaulting using a green bamboo
  use_null_inv: true
  video_length: 8
  width: 512
