enable_xformers_memory_efficient_attention: true
gradient_checkpointing: true
input_batch_size: 1
input_data:
  height: 512
  n_sample_frames: 8
  prompt: a child is riding a bike on the road
  sample_frame_rate: 1
  sample_start_idx: 0
  video_path: data/child-riding.mp4
  width: 512
mixed_precision: 'no'
output_dir: outputs/child-riding
pretrained_model_path: /root/autodl-tmp/cache_huggingface/huggingface/hub/models--runwayml--stable-diffusion-v1-5/
seed: 33
st_attn_idx: 0
use_sc_attn: true
use_st_attn: true
validation_data:
  guidance_scale: 7.5
  height: 512
  null_base_lr: 1e-2
  null_inner_steps: 1
  null_normal_infer: true
  null_uncond_ratio: -0.5
  num_inference_steps: 50
  num_inv_steps: 50
  prompts:
  - a lego child is riding a bike on the road
  - a child is riding a bike on the flooded road
  use_null_inv: true
  video_length: 8
  width: 512
