enable_xformers_memory_efficient_attention: true
gradient_checkpointing: true
input_batch_size: 1
input_data:
  height: 512
  n_sample_frames: 8
  prompt: A man with a dog skateboarding on the road
  sample_frame_rate: 3
  sample_start_idx: 0
  video_path: data/skateboard-dog.avi
  width: 512
mixed_precision: 'no'
output_dir: outputs/skateboard-dog
pretrained_model_path: /root/autodl-tmp/cache_huggingface/huggingface/hub/models--runwayml--stable-diffusion-v1-5/
seed: 33
st_attn_idx: 0
use_sc_attn: true
use_st_attn: true
validation_data:
  guidance_scale: 7.5
  height: 512
  null_base_lr: 1e-2
  null_inner_steps: 1
  null_normal_infer: true
  null_uncond_ratio: -0.5
  num_inference_steps: 50
  num_inv_steps: 50
  prompts:
  - A man with a dog skateboarding on the desert
  use_null_inv: true
  video_length: 8
  width: 512
