base_config: configs/default.yaml
generation:
  control: softedge
  control_scale: 0.4
  global_merge_ratio: 0.6
  global_rand: 0.5
  latents_path: ${work_dir}/latents
  local_merge_ratio: 0.9
  lora:
    adapter_name: pixel
    adapter_weights: 1.0
    pretrained_model_name_or_path_or_dict: artificialguybr/pixelartredmond-1-5v-pixel-art-loras-for-sd-1-5
    weight_name: PixelArtRedmond15V-PixelArt-PIXARFK.safetensors
  output_path: ${work_dir}
  prompt:
    pixelart: a man doing a trick on the ground in front of a crowd, pixel art, PixArFK.
  use_lora: true
height: 512
input_path: data/breakdance.mp4
inversion:
  force: true
  prompt: a man doing a trick on the ground in front of a crowd.
  save_intermediate: false
  save_path: ${work_dir}/latents
sd_version: '1.5'
width: 512
work_dir: outputs/breakdance
