device: cuda
enable_xformers_memory_efficient_attention: true
float_precision: fp16
generation:
  align_batch: true
  chunk_ord: mix-4
  chunk_size: 4
  control: pnp
  control_scale: 1.0
  frame_ids: null
  frame_range:
  - 0
  - 32
  - 1
  global_merge_ratio: 0.8
  global_rand: 0.5
  guidance_scale: 7.5
  latents_path: ${work_dir}/latents
  local_merge_ratio: 0.9
  lora_weight: 0.5
  merge_global: true
  n_timesteps: 50
  negative_prompt: ugly, blurry, low res
  output_path: ${work_dir}
  pnp_attn_t: 0.5
  pnp_f_t: 0.8
  pretrained_model_name_or_path_or_dict: /root/autodl-fs/vid_checkpoints/ratio_0.0001_rank_4/checkpoint-100000/
  prompt: null
  save_frame: true
  use_lora: true
height: 512
input_path: path/to/video
inversion:
  batch_size: 8
  control: none
  control_scale: 1.0
  force: false
  n_frames: null
  prompt: xxxx
  recon: false
  save_intermediate: false
  save_path: ${work_dir}/latents
  save_steps: 50
  steps: 50
  use_blip: false
model_key: null
sd_version: '1.5'
seed: 123
width: 512
work_dir: workdir
