base_config: configs/default.yaml
device: cuda
enable_xformers_memory_efficient_attention: true
float_precision: fp16
generation:
  control: pnp
  global_merge_ratio: 0.8
  global_rand: 0.5
  guidance_scale: 7.5
  latents_path: ${work_dir}/latents
  local_merge_ratio: 0.9
  n_timesteps: 50
  negative_prompt: ugly, blurry, low res
  output_path: ${work_dir}
  prompt:
    VG: a dog walking on the ground near a bush, Van Gogh style.
    desert: a dog walking in the desert near a bush.
height: 512
input_path: data/dog.mp4
inversion:
  n_frames: 32
  prompt: a dog walking on the ground near a bush.
  save_intermediate: true
  save_path: ${work_dir}/latents
  save_steps: 50
  steps: 50
sd_version: '1.5'
seed: 123
width: 512
work_dir: outputs/dog
