base_config: configs/default.yaml
generation:
  chunk_ord: rand
  control: none
  global_merge_ratio: 0.9
  local_merge_ratio: 0.9
  negative_prompt: ''
  prompt:
    origami: rainbow-colored origami flamingos standing in the water near a tree.
height: 512
input_path: data/flamingo.mp4
inversion:
  prompt: flamingos standing in the water near a tree.
sd_version: '1.5'
seed: 142857
width: 512
work_dir: outputs/flamingo
