base_config: configs/default.yaml
generation:
  control: depth
  control_scale: 1.0
  frame_range:
  - 64
  global_merge_ratio: 0.9
  global_rand: 0.1
  local_merge_ratio: 0.95
  prompt:
    vector: vector illustration of a tea pot pouring tea into a cup.
height: 512
input_path: autodl-fs/research/Tokenflow_adapter/TokenFlow/data/video7021/
inversion:
  prompt: a baseball batter hits a glass ball to the fence and a outfielder goes after
    it
  save_path: autodl-fs/research/VidToMe-main/data/
sd_version: '1.5'
width: 512
work_dir: outputs/tea-pour
